# Generated by Django 6.0.6 on 2026-06-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoApp',
        ),
    ]
